services:
  firmware:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    privileged: true
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: >
      bash -lc "
        mkdir -p build &&
        cd build &&
        cmake .. &&
        make -j &&
        ./solution/answer
      "
